/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.in.importador.dou.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ItemImportacao service. Represents a row in the &quot;IN_ItemImportacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.seatecnologia.in.importador.dou.model.impl.ItemImportacaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.seatecnologia.in.importador.dou.model.impl.ItemImportacaoImpl}.
 * </p>
 *
 * @author SEA Tecnologia
 * @see ItemImportacao
 * @see br.com.seatecnologia.in.importador.dou.model.impl.ItemImportacaoImpl
 * @see br.com.seatecnologia.in.importador.dou.model.impl.ItemImportacaoModelImpl
 * @generated
 */
@ProviderType
public interface ItemImportacaoModel extends BaseModel<ItemImportacao> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item importacao model instance should use the {@link ItemImportacao} interface instead.
	 */

	/**
	 * Returns the primary key of this item importacao.
	 *
	 * @return the primary key of this item importacao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item importacao.
	 *
	 * @param primaryKey the primary key of this item importacao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item importacao ID of this item importacao.
	 *
	 * @return the item importacao ID of this item importacao
	 */
	public long getItemImportacaoId();

	/**
	 * Sets the item importacao ID of this item importacao.
	 *
	 * @param itemImportacaoId the item importacao ID of this item importacao
	 */
	public void setItemImportacaoId(long itemImportacaoId);

	/**
	 * Returns the tipo item of this item importacao.
	 *
	 * @return the tipo item of this item importacao
	 */
	@AutoEscape
	public String getTipoItem();

	/**
	 * Sets the tipo item of this item importacao.
	 *
	 * @param tipoItem the tipo item of this item importacao
	 */
	public void setTipoItem(String tipoItem);

	/**
	 * Returns the data importacao of this item importacao.
	 *
	 * @return the data importacao of this item importacao
	 */
	public Date getDataImportacao();

	/**
	 * Sets the data importacao of this item importacao.
	 *
	 * @param dataImportacao the data importacao of this item importacao
	 */
	public void setDataImportacao(Date dataImportacao);

	/**
	 * Returns the identificador atualizacao of this item importacao.
	 *
	 * @return the identificador atualizacao of this item importacao
	 */
	@AutoEscape
	public String getIdentificadorAtualizacao();

	/**
	 * Sets the identificador atualizacao of this item importacao.
	 *
	 * @param identificadorAtualizacao the identificador atualizacao of this item importacao
	 */
	public void setIdentificadorAtualizacao(String identificadorAtualizacao);

	/**
	 * Returns the importado of this item importacao.
	 *
	 * @return the importado of this item importacao
	 */
	public boolean getImportado();

	/**
	 * Returns <code>true</code> if this item importacao is importado.
	 *
	 * @return <code>true</code> if this item importacao is importado; <code>false</code> otherwise
	 */
	public boolean isImportado();

	/**
	 * Sets whether this item importacao is importado.
	 *
	 * @param importado the importado of this item importacao
	 */
	public void setImportado(boolean importado);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ItemImportacao itemImportacao);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ItemImportacao> toCacheModel();

	@Override
	public ItemImportacao toEscapedModel();

	@Override
	public ItemImportacao toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}