/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.migrador.social.publisher.model.impl;

import aQute.bnd.annotation.ProviderType;

import br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao;
import br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacaoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ItemPublicacao service. Represents a row in the &quot;IN_ItemPublicacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ItemPublicacaoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemPublicacaoImpl}.
 * </p>
 *
 * @author SEA Tecnologia
 * @see ItemPublicacaoImpl
 * @see ItemPublicacao
 * @see ItemPublicacaoModel
 * @generated
 */
@ProviderType
public class ItemPublicacaoModelImpl extends BaseModelImpl<ItemPublicacao>
	implements ItemPublicacaoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item publicacao model instance should use the {@link ItemPublicacao} interface instead.
	 */
	public static final String TABLE_NAME = "IN_ItemPublicacao";
	public static final Object[][] TABLE_COLUMNS = {
			{ "itemPublicacaoId", Types.BIGINT },
			{ "entryId", Types.BIGINT },
			{ "postId", Types.VARCHAR },
			{ "publishDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "socialNetwork", Types.INTEGER },
			{ "itemMigracaoId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("itemPublicacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("postId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("socialNetwork", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("itemMigracaoId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table IN_ItemPublicacao (itemPublicacaoId LONG not null primary key,entryId LONG,postId VARCHAR(75) null,publishDate DATE null,modifiedDate DATE null,socialNetwork INTEGER,itemMigracaoId LONG)";
	public static final String TABLE_SQL_DROP = "drop table IN_ItemPublicacao";
	public static final String ORDER_BY_JPQL = " ORDER BY itemPublicacao.publishDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY IN_ItemPublicacao.publishDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(br.com.seatecnologia.migrador.social.publisher.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(br.com.seatecnologia.migrador.social.publisher.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(br.com.seatecnologia.migrador.social.publisher.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao"),
			true);
	public static final long ENTRYID_COLUMN_BITMASK = 1L;
	public static final long POSTID_COLUMN_BITMASK = 2L;
	public static final long PUBLISHDATE_COLUMN_BITMASK = 4L;
	public static final long SOCIALNETWORK_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(br.com.seatecnologia.migrador.social.publisher.service.util.ServiceProps.get(
				"lock.expiration.time.br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao"));

	public ItemPublicacaoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _itemPublicacaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setItemPublicacaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _itemPublicacaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemPublicacao.class;
	}

	@Override
	public String getModelClassName() {
		return ItemPublicacao.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("itemPublicacaoId", getItemPublicacaoId());
		attributes.put("entryId", getEntryId());
		attributes.put("postId", getPostId());
		attributes.put("publishDate", getPublishDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("socialNetwork", getSocialNetwork());
		attributes.put("itemMigracaoId", getItemMigracaoId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long itemPublicacaoId = (Long)attributes.get("itemPublicacaoId");

		if (itemPublicacaoId != null) {
			setItemPublicacaoId(itemPublicacaoId);
		}

		Long entryId = (Long)attributes.get("entryId");

		if (entryId != null) {
			setEntryId(entryId);
		}

		String postId = (String)attributes.get("postId");

		if (postId != null) {
			setPostId(postId);
		}

		Date publishDate = (Date)attributes.get("publishDate");

		if (publishDate != null) {
			setPublishDate(publishDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer socialNetwork = (Integer)attributes.get("socialNetwork");

		if (socialNetwork != null) {
			setSocialNetwork(socialNetwork);
		}

		Long itemMigracaoId = (Long)attributes.get("itemMigracaoId");

		if (itemMigracaoId != null) {
			setItemMigracaoId(itemMigracaoId);
		}
	}

	@Override
	public long getItemPublicacaoId() {
		return _itemPublicacaoId;
	}

	@Override
	public void setItemPublicacaoId(long itemPublicacaoId) {
		_itemPublicacaoId = itemPublicacaoId;
	}

	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_columnBitmask |= ENTRYID_COLUMN_BITMASK;

		if (!_setOriginalEntryId) {
			_setOriginalEntryId = true;

			_originalEntryId = _entryId;
		}

		_entryId = entryId;
	}

	public long getOriginalEntryId() {
		return _originalEntryId;
	}

	@Override
	public String getPostId() {
		if (_postId == null) {
			return "";
		}
		else {
			return _postId;
		}
	}

	@Override
	public void setPostId(String postId) {
		_columnBitmask |= POSTID_COLUMN_BITMASK;

		if (_originalPostId == null) {
			_originalPostId = _postId;
		}

		_postId = postId;
	}

	public String getOriginalPostId() {
		return GetterUtil.getString(_originalPostId);
	}

	@Override
	public Date getPublishDate() {
		return _publishDate;
	}

	@Override
	public void setPublishDate(Date publishDate) {
		_columnBitmask = -1L;

		if (_originalPublishDate == null) {
			_originalPublishDate = _publishDate;
		}

		_publishDate = publishDate;
	}

	public Date getOriginalPublishDate() {
		return _originalPublishDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public int getSocialNetwork() {
		return _socialNetwork;
	}

	@Override
	public void setSocialNetwork(int socialNetwork) {
		_columnBitmask |= SOCIALNETWORK_COLUMN_BITMASK;

		if (!_setOriginalSocialNetwork) {
			_setOriginalSocialNetwork = true;

			_originalSocialNetwork = _socialNetwork;
		}

		_socialNetwork = socialNetwork;
	}

	public int getOriginalSocialNetwork() {
		return _originalSocialNetwork;
	}

	@Override
	public long getItemMigracaoId() {
		return _itemMigracaoId;
	}

	@Override
	public void setItemMigracaoId(long itemMigracaoId) {
		_itemMigracaoId = itemMigracaoId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ItemPublicacao.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemPublicacao toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ItemPublicacao)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemPublicacaoImpl itemPublicacaoImpl = new ItemPublicacaoImpl();

		itemPublicacaoImpl.setItemPublicacaoId(getItemPublicacaoId());
		itemPublicacaoImpl.setEntryId(getEntryId());
		itemPublicacaoImpl.setPostId(getPostId());
		itemPublicacaoImpl.setPublishDate(getPublishDate());
		itemPublicacaoImpl.setModifiedDate(getModifiedDate());
		itemPublicacaoImpl.setSocialNetwork(getSocialNetwork());
		itemPublicacaoImpl.setItemMigracaoId(getItemMigracaoId());

		itemPublicacaoImpl.resetOriginalValues();

		return itemPublicacaoImpl;
	}

	@Override
	public int compareTo(ItemPublicacao itemPublicacao) {
		int value = 0;

		value = DateUtil.compareTo(getPublishDate(),
				itemPublicacao.getPublishDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ItemPublicacao)) {
			return false;
		}

		ItemPublicacao itemPublicacao = (ItemPublicacao)obj;

		long primaryKey = itemPublicacao.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ItemPublicacaoModelImpl itemPublicacaoModelImpl = this;

		itemPublicacaoModelImpl._originalEntryId = itemPublicacaoModelImpl._entryId;

		itemPublicacaoModelImpl._setOriginalEntryId = false;

		itemPublicacaoModelImpl._originalPostId = itemPublicacaoModelImpl._postId;

		itemPublicacaoModelImpl._originalPublishDate = itemPublicacaoModelImpl._publishDate;

		itemPublicacaoModelImpl._originalSocialNetwork = itemPublicacaoModelImpl._socialNetwork;

		itemPublicacaoModelImpl._setOriginalSocialNetwork = false;

		itemPublicacaoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ItemPublicacao> toCacheModel() {
		ItemPublicacaoCacheModel itemPublicacaoCacheModel = new ItemPublicacaoCacheModel();

		itemPublicacaoCacheModel.itemPublicacaoId = getItemPublicacaoId();

		itemPublicacaoCacheModel.entryId = getEntryId();

		itemPublicacaoCacheModel.postId = getPostId();

		String postId = itemPublicacaoCacheModel.postId;

		if ((postId != null) && (postId.length() == 0)) {
			itemPublicacaoCacheModel.postId = null;
		}

		Date publishDate = getPublishDate();

		if (publishDate != null) {
			itemPublicacaoCacheModel.publishDate = publishDate.getTime();
		}
		else {
			itemPublicacaoCacheModel.publishDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			itemPublicacaoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			itemPublicacaoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		itemPublicacaoCacheModel.socialNetwork = getSocialNetwork();

		itemPublicacaoCacheModel.itemMigracaoId = getItemMigracaoId();

		return itemPublicacaoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{itemPublicacaoId=");
		sb.append(getItemPublicacaoId());
		sb.append(", entryId=");
		sb.append(getEntryId());
		sb.append(", postId=");
		sb.append(getPostId());
		sb.append(", publishDate=");
		sb.append(getPublishDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", socialNetwork=");
		sb.append(getSocialNetwork());
		sb.append(", itemMigracaoId=");
		sb.append(getItemMigracaoId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>itemPublicacaoId</column-name><column-value><![CDATA[");
		sb.append(getItemPublicacaoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>entryId</column-name><column-value><![CDATA[");
		sb.append(getEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postId</column-name><column-value><![CDATA[");
		sb.append(getPostId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publishDate</column-name><column-value><![CDATA[");
		sb.append(getPublishDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>socialNetwork</column-name><column-value><![CDATA[");
		sb.append(getSocialNetwork());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemMigracaoId</column-name><column-value><![CDATA[");
		sb.append(getItemMigracaoId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ItemPublicacao.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ItemPublicacao.class, ModelWrapper.class
		};
	private long _itemPublicacaoId;
	private long _entryId;
	private long _originalEntryId;
	private boolean _setOriginalEntryId;
	private String _postId;
	private String _originalPostId;
	private Date _publishDate;
	private Date _originalPublishDate;
	private Date _modifiedDate;
	private int _socialNetwork;
	private int _originalSocialNetwork;
	private boolean _setOriginalSocialNetwork;
	private long _itemMigracaoId;
	private long _columnBitmask;
	private ItemPublicacao _escapedModel;
}