/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.migrador.social.publisher.model.impl;

import aQute.bnd.annotation.ProviderType;

import br.com.seatecnologia.migrador.social.publisher.model.ItemPublicacao;
import br.com.seatecnologia.migrador.social.publisher.service.ItemPublicacaoLocalServiceUtil;

/**
 * The extended model base implementation for the ItemPublicacao service. Represents a row in the &quot;IN_ItemPublicacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemPublicacaoImpl}.
 * </p>
 *
 * @author SEA Tecnologia
 * @see ItemPublicacaoImpl
 * @see ItemPublicacao
 * @generated
 */
@ProviderType
public abstract class ItemPublicacaoBaseImpl extends ItemPublicacaoModelImpl
	implements ItemPublicacao {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item publicacao model instance should use the {@link ItemPublicacao} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ItemPublicacaoLocalServiceUtil.addItemPublicacao(this);
		}
		else {
			ItemPublicacaoLocalServiceUtil.updateItemPublicacao(this);
		}
	}
}